# Generated by Django 4.1.7 on 2023-04-30 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('timeline_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timeline_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('timeline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline_app.timeline')),
            ],
        ),
    ]
